### ISSUE TITLE
Please add some basic docs or overview :-)

### ISSUE THREAD

**Issue by aspiers** [akirak/org-memento#6]
Hi there, this sounds like a really interesting project but unfortunately I can't easily tell what it does :laughing:  Even if you don't have time to fully document, is there any chance you could expand the README with at least a brief summary so that we can judge whether it's worth us taking a closer look?  Thanks!

**Comment by akirak** [comment]
Hello @aspiers, thanks for your interest. As I have written in the README, this project is not meant for general use. Still, it would be important to explain what is does and the current overall state of the project. I have just updated the readme, so please take a look at it.

**Comment by aspiers** [comment]
Thanks so much, that's great :-)

**Comment by aspiers** [comment]
By the way, I was perhaps thinking along similar lines.  I have a dream of an org-mode extension which can automatically generate an agenda for a day based on the priorities / time estimates / `SCHEDULED` and `DEADLINE` timestamps for all the TODOs.  It would avoid causing conflicts with events synced from external calendars via solutions such as https://github.com/dengste/org-caldav or https://github.com/myuhe/org-gcal.el.

**Comment by akirak** [comment]
>  I have a dream of an org-mode extension which can automatically generate an agenda for a day based on the priorities / time estimates / SCHEDULED and DEADLINE timestamps for all the TODOs. 

There are https://github.com/ichernyshovvv/org-timeblock and https://github.com/dmitrym0/org-hyperscheduler/ which provide an excellent visualization of the user's timeline inside Emacs. Although I haven't tried any of them, the former looks good. I would recommend it if it fits your mental model.

The point of `org-memento` is that it groups activities into a nested structure using [taxy.el](https://github.com/alphapapa/taxy.el/). I tried to implement complex grouping that org-agenda + [org-super-agenda](https://github.com/alphapapa/org-super-agenda) cannot do, and it turns out that taxy is convenient for building a hierarchy of lists, grouped in a certain way.
